### ISSUE TITLE
Force turn off discrete GPU on startup

### ISSUE THREAD

**Issue by hadess** [hadess/switcheroo-control#1]
From http://article.gmane.org/gmane.comp.video.dri.devel/149144

```
GD and DIGD switch to the integrated GPU and also turn off the discrete
GPU. However if the machine is already switched to the integrated GPU,
the commands are no-ops and the discrete GPU is not turned off.

In other words you need to check (by reading the switch file) which GPU
the machine is switched to. If it's the integrated GPU, write OFF to the
switch file. If it's the discrete GPU, write DIGD to the switch file.

Once runtime pm works, writing DIGD is sufficient.
```

**Comment by Firstyear** [comment]
I think this is affecting me as I have a MBP 8,2, and efi set to use IGD by default. 

switcheroo-control does "nothing" for me, because of this issue, I have to still manually disable the discreet card.

**Comment by hadess** [comment]
This should really be done by the firmware (BIOS/UEFI/other), or in the worst case by the kernel, not by a helper.
