### ISSUE TITLE
switcheroo control is missing dependency on on also

### ISSUE THREAD

**Issue by Firstyear** [hadess/switcheroo-control#10]
If the systm starts on IGD, and discreet in enabled, if you DO NOT turn of the discreet before alsa starts, the system locks up

switcheroo control must depend on:

```
Before=multi-user.target display-manager.target alsa-restore.service alsa-state.service
```

To correctly ensure that discreet/igd is disabled before alsa starts to prevent lockup.

This can be reproduced on mbp 8,2 with efi set to intel.

**Comment by hadess** [comment]
Was fixed in:
```
commit 3592c1c47239a022f83796522b330a244246bf32
Author: Bastien Nocera <hadess@hadess.net>
Date:   Tue Jun 11 19:32:23 2019 +0200

    data: Launch before some ALSA scripts
    
    Otherwise ALSA might use the enabled GPU's audio out, and refuse to
    relinquish it before boot.
```
