### ISSUE TITLE
switcheroo control should ship method to fix grub loader

### ISSUE THREAD

**Issue by Firstyear** [hadess/switcheroo-control#11]
If the system boots on igd with grub set to "rhgb", then display-manager will not start and system locks (even if you OFF the discreet card, or leave it enabled)

As a result, the only method to boot is to remove rhgb from grub to prevent display change issues.

switcheroo-control should disable "rhgb" on systems to prevent display locking issues on startup.

**Comment by hadess** [comment]
I don't think that it's switcheroo-control's job to disable rhgb to work-around a kernel bug. I would advise reaching out to Lukas Wunner (listed in the kernel's `MAINTAINERS` file) so he can help diagnose and fix those problems.
