### ISSUE TITLE
Doesn't work with SecureBoot enabled

### ISSUE THREAD

**Issue by hadess** [hadess/switcheroo-control#12]
From https://bugzilla.redhat.com/show_bug.cgi?id=1476366
```
As it stands, this is working as expected. When secureboot is on, debugfs is
locked down. Per the patch, "Normal device interaction should be done through
configfs or a miscdev, not debugfs." I think something needs to be done for
vgaswitcheroo for secureboot.
```

We'll need to adapt to whatever the new method will be.

**Comment by develart-projects** [comment]
Is this component somehow maintained here, please? I just want to ensure, if this bug is reported in the right place, thank you.

**Comment by hadess** [comment]
It is maintained, but it's a problem in the kernel, which we can't fix "from here", and I have no time to try and convince kernel developers to do anything about this.

**Comment by develart-projects** [comment]
And using configfs is not an option here, please ?

**Comment by hadess** [comment]
"Using configfs" wouldn't fix anything, the configuration in question isn't exported through configfs in the kernel, but through debugfs. See `drivers/gpu/vga/vga_switcheroo.c` in the kernel.

**Comment by hadess** [comment]
*Mind confuses SELinux and SecureBoot*

**Comment by hadess** [comment]
The work-around doesn't work.
