### ISSUE TITLE
Doesn't work on Dell 3576

### ISSUE THREAD

**Issue by waleedyt** [hadess/switcheroo-control#14]
Hi,
My Linux system boots to a black screen when this package is installed, I have tested this issue on Fedora 28, 29 Beta, Ubuntu 18.04/18.04.1 and Ubuntu 18.10 Beta. My system is 8th gen core i7 and has AMD Radeon 520 as discrete card. Once i remove this package, i can boot and start the system fine. 
Is it a known bug? if so any hot fix i can do with? if not please let me know how i can help to help debug this and if i need to provide anything else.

**Comment by waleedyt** [comment]
I figured the problem out. Solution and problem was also documented in the read me. For future reference the problem was that it was trying to automatically switch to intel card at startup where as i guess it(the switch) isn't supported by my laptop firmware. Adding 

> xdg.force_integrated=0

to kernel command line parameters did the trick.

**Comment by hadess** [comment]
> I figured the problem out. Solution and problem was also documented in the read me. For future reference the problem was that it was trying to automatically switch to intel card at startup where as i guess it(the switch) isn't supported by my laptop firmware.

That means that there's a kernel bug here.

**Comment by waleedyt** [comment]
Do I need to report it somewhere?

**Comment by hadess** [comment]
> Do I need to report it somewhere?

Well, you most probably do if you want it to be fixed.

**Comment by waleedyt** [comment]
Sorry that came out wrong. What I wanted to ask was if it was some well
known kernel bug! I ll report it.

**Comment by hadess** [comment]
> Sorry that came out wrong. What I wanted to ask was if it was some well known kernel bug! I ll report it.

It's not a kernel bug that I know, no.
