### ISSUE TITLE
Fail to start on MacBook 6,2

### ISSUE THREAD

**Issue by hfiguiere** [hadess/switcheroo-control#4]
switcheroo-control fail to start on MacBook 6,2

```
# cat /sys/kernel/debug/vgaswitcheroo/switch       
0:DIS-Audio: :Pwr:0000:01:00.1
1:IGD: :Pwr:0000:00:02.0
2:DIS:+:Pwr:0000:01:00.0
```

**Comment by hadess** [comment]
It's a Fedora packaging bug. The service is not enabled by the post-install scripts or presets. See:
https://bugzilla.redhat.com/show_bug.cgi?id=1389762

**Comment by hfiguiere** [comment]
ah. that would explain. thanks !
