### ISSUE TITLE
Missing documention on developer.gnome.org

### ISSUE THREAD

**Issue by jbicha** [hadess/switcheroo-control#6]
[README.md](https://github.com/hadess/switcheroo-control/blob/master/README.md) links to https://developer.gnome.org/switcheroo-control/1.0/ but that URL isn't live yet.

**Comment by hadess** [comment]
A combination of autotools and gtk-doc are conspiring to keep generated gtk-doc out of the tarball, even though `--enable-gtk-doc` is passed to the configure during `make dist`.

Moving to meson wouldn't be much better either:
https://github.com/mesonbuild/meson/issues/2166

**Comment by hadess** [comment]
Documentation was added to the 1.2 tarball through 41177cc5b1d6bc4776c96993deab579ec0f99cf4

**Comment by hadess** [comment]
And documentation on GNOME.org should be done in:
https://git.gnome.org/browse/library-web/commit/?id=98cd63188cd3348e9805704580c5bfbfdf57e154

With 899d1b320abb236bf60bf836993b5eb31ac1f767 taking care of the changing version numbers.

**Comment by hadess** [comment]
The docs: https://developer.gnome.org/switcheroo-control/1.2/
