### ISSUE TITLE
After resume discrete card must be turned off again

### ISSUE THREAD

**Issue by Firstyear** [hadess/switcheroo-control#9]
After a resume on an MBP 8,2, the discreet card reactivates. 

After a result the "inactive" card should be powered off, IE resume should trigger "OFF > vgaswitcheroo" to guarantee the discreet is disabled,

**Comment by hadess** [comment]
I'm afraid that this isn't something that switcheroo-control can, or should be doing. The firmware or the kernel should be responsible for disabling the discrete GPU when it's not in use.
